---
# defaults file for setup_etcd

ansible_user                    : aladmin 
# ansible_ssh_private_key_file    : /home/vponomarev/.ssh/id_rsa.pub 
ansible_ssh_pass                : 08-Stend-2017

# remote directories
etcd_dir                        : /opt/etcd-3.4.22


# data cluster etcd
etcd_token                      : cluster-etcd-upak
etcd_port_server                : 2380
etcd_port_client                : 2379

etcd_name_1                     : etcd-1
etcd_ip_1                       : 192.168.119.61

etcd_name_2                     : etcd-2
etcd_ip_2                       : 192.168.119.62

etcd_name_3                     : etcd-3
etcd_ip_3                       : 192.168.119.63

etcd_initial_1                  : "{{ etcd_name_1 }}=http://{{ etcd_ip_1 }}:{{ etcd_port_server }}"
etcd_initial_2                  : "{{ etcd_name_2 }}=http://{{ etcd_ip_2 }}:{{ etcd_port_server }}"
etcd_initial_3                  : "{{ etcd_name_3 }}=http://{{ etcd_ip_3 }}:{{ etcd_port_server}}"

etcd_initial_cluster            : "{{ etcd_initial_1 }},{{ etcd_initial_2 }},{{ etcd_initial_3 }}"
        
