---
# vars file for cluster-pg

ansible_user                    : aladmin
ansible_ssh_pass                : 08-Stend-2017 
#ansible_ssh_private_key         : /home/vponomarev/.ssh/id_rsa 
ansible_port                    : 22

